formatter: "md table"
output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
recursive:
  enabled: true
settings:
  hide-empty: true
